export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const GET_DETAILS_OF_POST = 'GET_DETAILS_OF_POST'; //
export const GET_COMMENTS_OF_POST = 'GET_COMMENTS_OF_POST'; //
export const VOTE_FOR_POST = 'VOTE_FOR_POST'; //

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_POSTS_FOR_CATEGORY = 'GET_POSTS_FOR_CATEGORY';

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_DETAILS_OF_COMMENT = 'GET_DETAILS_OF_COMMENT'; //
export const VOTE_FOR_COMMENT = 'VOTE_FOR_COMMENT'; //
export const DELETE_COMMENT = 'DELETE_COMMENT';
